### ISSUE TITLE
PR flow?

### ISSUE THREAD

**Issue by cchantep** [zengularity/query-monad#5]
Merge pending branch in master and setup a flow with new feature/refactor in PR branch? (with master being protected)

**Comment by stankoua** [comment]
I start a contribution guide in PR #7. We can discuss about conventions and worflow.

**Comment by stankoua** [comment]
I don't have access to the project settings, so I can't define merge protection as describe in this guide.

**Comment by stankoua** [comment]
Done as PR #7 is closed
